# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # ใช้เวอร์ชันล่าสุดเสมอ

    - name: Set up Go
      uses: actions/setup-go@v4  # ใช้เวอร์ชันล่าสุดเสมอ
      with:
        go-version: '^1.21'  # ใช้เวอร์ชัน Go ล่าสุดที่รองรับ

    - name: Install-Golang-Dependencies
      run: go mod download

    - name: Build Golang Application
      run: go build -o build/web-booking -v

    - name: Display-Build-Golang-App
      run: ls -R build/

    - name: Create-Env-File
      run: 'echo "APIKey=${{ secrets.APIKey }}" > build/.env'

    - name: Copy-Build-Golang-App
      uses: appleboy/scp-action@master
      with:
        host: '${{ secrets.SERVER_IP }}'
        username: '${{ secrets.SSH_USERNAME }}'
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        port: '${{ secrets.SERVER_PORT }}'
        source: build/
        target: /root/web-booking
